---
title: "Reproducible Research: Peer Assessment 1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#Loading and preprocessing the data
activity <- read.csv("activity.csv")
activity$date <- as.Date(activity$date)

#What is mean total number of steps taken per day?
library(dplyr)

# Total steps per day
daily_steps <- activity %>%
  group_by(date) %>%
  summarize(total_steps = sum(steps, na.rm = TRUE))

# Histogram
hist(daily_steps$total_steps, main="Total Steps per Day", xlab="Steps", col="blue")

# Mean and median
mean_steps <- mean(daily_steps$total_steps, na.rm = TRUE)
median_steps <- median(daily_steps$total_steps, na.rm = TRUE)

mean_steps
median_steps


#What is the average daily activity pattern?
avg_interval <- activity %>%
  group_by(interval) %>%
  summarize(mean_steps = mean(steps, na.rm = TRUE))

# Time series plot
plot(avg_interval$interval, avg_interval$mean_steps, type="l", 
     main="Average Steps per 5-Minute Interval", 
     xlab="Interval", ylab="Average Steps")

# Interval with max average steps
avg_interval[which.max(avg_interval$mean_steps), ]

#Imputing missing values
# Total missing values
sum(is.na(activity$steps))

# Impute with mean for that interval
activity_imputed <- activity
interval_means <- avg_interval$mean_steps
names(interval_means) <- avg_interval$interval

activity_imputed$steps <- ifelse(is.na(activity_imputed$steps),
                                 interval_means[as.character(activity_imputed$interval)],
                                 activity_imputed$steps)

# Recalculate daily totals
daily_steps_imputed <- activity_imputed %>%
  group_by(date) %>%
  summarize(total_steps = sum(steps))

# Histogram after imputation
hist(daily_steps_imputed$total_steps, main="Total Steps per Day (Imputed)", 
     xlab="Steps", col="green")

# Mean and median
mean(daily_steps_imputed$total_steps)
median(daily_steps_imputed$total_steps)


#Are there differences in activity patterns between weekdays and weekends?
activity_imputed$day_type <- ifelse(weekdays(activity_imputed$date) %in% 
                                       c("Saturday", "Sunday"), "weekend", "weekday")
activity_imputed$day_type <- as.factor(activity_imputed$day_type)

library(lattice)
avg_by_daytype <- activity_imputed %>%
  group_by(interval, day_type) %>%
  summarize(mean_steps = mean(steps))

# Panel plot
xyplot(mean_steps ~ interval | day_type, data = avg_by_daytype, type = "l",
       layout = c(1,2), xlab="Interval", ylab="Steps",
       main="Average Steps by Interval: Weekday vs Weekend")



